* RQ1: What type of data has been explored by the POI recommendation models?

Almost all works use geographical feature to model a solution to all the problems of POI recommendation, the over-usage of geolocation usage shows the importance of considering and modeling a good model for the POI recommendation \cite{}. Studies that dont explicily uses the geolocation may through implicit features of user preference and POI latent factors consider it cite:guo2019location, but are not considered that it uses geographical information.

The second most used information is the user's preferences that is addressed by many works as latent factors\cite{}, this is mostly present in methods that use factorization\cite{}. There are other works that refers to user preference as the gender, categories consumed, age, context and other many personal information. In general all this information are modeled by some studies varying with the time\cite{} and in combination with context(ex: weather)\cite{}. A recent work explored image in POI recommendation in Instagram dataset \cite{}.

Social is the third most used type of information, it makes sense as most of the studies are using User-based (User-User) Collaborative-Filtering, and is a good information in the sense that users are most likely to match with a friend or equal user preference, but it is not so trustworthy if using friend information of user because the friends may have different tastes, and because of this most of the works consider equal user more than an explicitly friendship like \cite{}. Social information is mostly used in the problem of Group POI recommendation.

The fourth most used information, Temporal, is being severally explored in recent works \cite{}(HiRecS,...) and are achieving excellent results, it is most used in problems like Next Poi, Time-aware and recently in traditional Poi recommendation. This information is being used in combination with social (Population data) and category information to model a preference to visit certain POIs of some category in certain times of the day. (Need to put some examples inside the text)

Categorical information is mostly used to address and match the user tastes. Sequential information is mostly modeled as the cost and probability of transition of POIs and principally is used in combination with categorical and geographical information. The problems that most use sequential information is Next POI and POI Tour.

Textual information is not much used because of it's reproducibility and cost but several works are exploring it benefits\cite{}, normally textual information is used to map the user preferences.

* RQ2: Which models have are been effective considering the accuracy of their results?

To analyse good results of a method it is important x factors: (1) What problem is being solved; (2) The method is being compared with baselines of the field(problem); (3) It is using a common and stated evaluation in the problem type field. We need first to analyse each field of POI recommendation problem. Some works explore a purely new POI problem like \cite{} and they are not going to be considered but are works that need attention of the community. These works explore the following problem:

- Requirement-aware: Given a requirement of the user the recommendation system will recommend items that satisfies this requirement. These requirements are explicitly specified to the system.
- Category-aware: In this problem first is given the user category preference and this information is used to recommend.
- Effective Path: A effective path is a set of POIs that is not homogeneous and have associations among them(e.g. {attractions,shop,restaurant} can be considered as an effective path).
- Group POI rec: Given a set of users need to give for them a list of POIs that match their preferences. It is a extremely difficult problem given that people have different tastes.
- Future visitor: This is the problem of recognizing the potential visitors who will visit a POI in the next hours. 
- Friend: Recommend a friend through the user information.
- Tour: Recommend a set of POIs that are likely to be visited in sequence by a user. Mostly all of the methods recommend with some constraint in the time or distance.
- Group POI Tour: Recommend a set of POIs that are probable to be visited in a tour by a set of users.
- Group City recommendation: Recommend a city to a group of users.

To the best of our knowledge we could find the following problems:

- POI: Recommend a POI that is likely to be visited by a user.
- Next POI: Is the problem that given a user and his location recommend POIs that are likely to be visited in the next time interval.
- Time-aware: Recommend POIs given a time that are likely to be visited.
- In-town/Out-of-town: Recommend POIs to a user in another location(city,town) that is not his home location(city,town).
   


** POI recommendation

   PACE cite:yang17_bridg_collab_filter_semi_super_learn and Geo-Teaser cite:zhao18_geo_teaser are the most prominent methods in POI recommendation. PACE and Geo-Teaser presents a consistent evaluation of accuracy with all the traditional baselines of POI recommendation. Others works presents similar baselines cite:ren17_contex_aware_probab_matrix_factor,aliannejadi18_person_contex_aware_point_inter_recom,wang18_exploit_poi_specif_geogr_influen,qian19_spatiot_repres_learn_trans_based_poi_recom.
   
   But others methods evaluated comparing with these robust recent methods cite:Ma2018,zhou19_adver_point_inter_recom and achieve even more accuracy.

   Other method expanded the field with use of image information cite:wang17_what_your_images_reveal.

   A work presented use of trust enhancement in social networks, exploring a new methodology cite:logesh17_reliab_point_inter_recom_based.
   
   Many methods compare they results with only the same type of model.

** Time-aware

   Compare in general with traditional POI recommender, there is no difference.
   
   With the recent increase in temporal information usage in models is difficult to distinguish time-aware POI recommendation.

** Next POI

   There is a crescent interest in Next POI recommendation and several works explorated interesting models to solve this problem cite:zhao18_stell,feng2017poi2vec,Zhao2018WhereTG. The most cited is STELLAR cite:zhao18_stell and a recent work cite:chang18_conten_aware_hierar_point_inter has showed several baselines, STELLAR included and others recent works, and presents excellent results and good accuracy results.
   The second most relevant in terms of citations in the Next POI problem is the POI2Vec article that presents good evaluation in Next POI and Future Visitor problems comparing with the state of art methods. cite:feng2017poi2vec

** In-/Out-of-town

   In this problem we could only find 3 works, all of them from 2017 cite:wang2017location,pham17_gener_model_out_region_recom,yin17_spatial_aware_hierar_collab_deep. All of them develop some kind or based on a probability model and are using sequential, textual, social, user preference and geographical informations. This field is not receiving enough atention in the last years and we could not find many works to give a good point they are missing because of the lack of research, but is evident that any of these works explored the categorical and temporal information that is receiving so much atention in other problems.

** Tour
   
   Field with several lack of works comparating with each other, most of the works implement they own basic baselines (e.g. UCF, ICF, MostPopular and etc)
   
   The works with more relevance are respectively cite:lim17_person_trip_recom_touris_based,vijayakumar19_effec_knowl_based_recom_system,logesh2019exploring,logesh2019efficient,rakesh17_probab_social_sequen_model_tour_recom,liang18_top_route_searc_submod_model,baral18_close,debnath18_prefer_aware_travel_route_recom_tempor_influen,bin2019personalized,bewley2019tour,chen2019context,huang2019dynamic.

* RQ3: What combinations of methods have not yet been explored?
  
  Hybrid methods explore multiple types of models simultaneously cite:logesh2019exploring,lu17_person_locat_recom_by_aggreg.

  There is a lack in the evaluation of accuracy in several works that not evaluate with a objective metric if the gain of accuracy is significative (Most of them give a extremely low gain compared to baselines).

  
  

bibliographystyle:plain
bibliography:../doc.bib
